# Generated by Django 5.2.1 on 2025-05-16 03:23

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to=api.models.user_profile_upload_path)),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact must be in PH format (e.g. 09123456789 or +639123456789)', regex='^(09|\\+639)\\d{9}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
