# Generated by Django 5.2.1 on 2025-05-19 17:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=api.models.product_image_upload_path)),
                ('product_name', models.CharField(max_length=45)),
            ],
        ),
    ]
