# Generated by Django 5.2.1 on 2025-05-19 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveIntegerField()),
                ('product_quantity', models.PositiveBigIntegerField()),
                ('color_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productColor', to='api.color')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productName', to='api.product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productType', to='api.type')),
                ('size_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizeLabel', to='api.size')),
            ],
        ),
    ]
